# Generated by Django 4.0.6 on 2022-07-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='health_rating',
            field=models.CharField(choices=[('TS', 'TummySafe'), ('TC', 'TummyCautious'), ('TSC', 'TummyScared'), ('TN', 'TummyNope')], default=None, max_length=3),
        ),
        migrations.AddField(
            model_name='place',
            name='service_rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='place',
            name='taste_rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=0, max_length=1),
        ),
    ]
