# Generated by Django 4.0.6 on 2022-07-24 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_place_name_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=50)),
                ('address_line', models.CharField(max_length=255)),
                ('address_line2', models.CharField(max_length=255)),
                ('state_province', models.CharField(max_length=150)),
                ('town_city', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.address'),
            preserve_default=False,
        ),
    ]
