# Generated by Django 4.0.6 on 2022-07-24 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_address_place_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='address',
        ),
    ]
