# Generated by Django 4.0.6 on 2022-07-24 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_place_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.address'),
            preserve_default=False,
        ),
    ]
