# Generated by Django 4.0.6 on 2022-07-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_place_user_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address_line',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='place',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address Continued (optional)'),
        ),
        migrations.AlterField(
            model_name='place',
            name='postcode',
            field=models.CharField(max_length=50, verbose_name='Postal Code '),
        ),
        migrations.AlterField(
            model_name='place',
            name='state_province',
            field=models.CharField(max_length=150, verbose_name='State or Province'),
        ),
        migrations.AlterField(
            model_name='place',
            name='town_city',
            field=models.CharField(max_length=150, verbose_name='City'),
        ),
    ]
